// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('t1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('t1', async function() {
    await driver.get("https://gost-grants-tools-staging.onrender.com/")
    await driver.manage().window().setRect({ width: 1699, height: 1002 })
    await driver.findElement(By.linkText("My Grants")).click()
    assert(await driver.findElement(By.css("tbody > tr:nth-child(1) > .table-dark")).getText() == "HHS-2021-IHS-TPI-0002")
    await driver.findElement(By.css(".page-item:nth-child(3) > .page-link")).click()
    await driver.findElement(By.css(".active > .page-link")).click()
    await driver.findElement(By.linkText("Grants")).click()
    {
      const element = await driver.findElement(By.css(".b-table-sticky-header"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".b-table-sticky-header"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".b-table-sticky-header"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
  })
})
